### ISSUE TITLE
E-mail it is not triggering automatically 

### ISSUE THREAD

**Issue by hugocostadev** [vtex-apps/availability-notify#13]
Hey, how's it going?

I was testing the Availability Notify app, I managed to complete the test and configure the schema, but as it's not well documented, I don't know if I missed any important steps.
The only way I'm able to trigger the emails is by doing a GET on one of these endpoints:

- {{accountName}}.myvtex.com/availability-notify/process-unsent-requests

- {{accountName}}.myvtex.com/availability-notify/process-all-requests

I've already waited almost 12 hours for the email to be sent, but I don't think there should be a JOB that triggers the emails when the stock arrives, or I did something wrong haha, could you tell me?

Workspace: https://hugodev--brmotorolaiotest.myvtex.com/smartphone-moto-g-5g/p

Thanks for your attention.

**Comment by btalma** [comment]
Hi, Hugo.  The app listens for notifications from the Catalog Broadcaster for inventory updates.  I do not think that the notifications are sent to workspaces, so the emails will only be automatically triggered in master.

**Comment by hugocostadev** [comment]
Thanks a lot @btalma  worked pretty well on production!
